"""site_builder.py — storyboard envelope -> the four required site files.

This is the node the spec named (§6.2 run_visual_builder_agent / publish) and the
repo was missing: it turns the visual stage's storyboard into a self-contained,
SANDBOX-SAFE mini-site — index.html, styles.css, script.js, metadata.json — that
passes app.services.site_validator (the §7.5/§11 gate) by construction:

  - CSP meta is imported VERBATIM from the validator (STRICT_CSP_HEADER) so the
    declared policy can never drift from the enforced one.
  - script-src 'self' => zero inline executable JS; all behavior is in script.js,
    events bound via addEventListener (NO on* handlers the validator forbids).
  - connect-src 'none' + no fetch/XHR/WebSocket/eval/Function => no egress, no
    dynamic code. Scene data rides an inert <script type="application/json"> block
    (data, not code) with '<' escaped so chapter text can't break out of it.
  - viewport meta + local-only refs (styles.css, script.js) => mobile + offline.

build_site(storyboard, pack, verdict, meta) -> {filename: text}. Pure stdlib.
"""
from __future__ import annotations

import base64
import html
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from app.services.site_validator import STRICT_CSP_HEADER  # noqa: E402


def build_site(storyboard: dict, pack: dict, verdict: dict, meta: dict) -> dict:
    """Render the four files as a {name: content} dict. `meta` supplies the
    metadata.json identity fields (experience_id, job_id, band_room_id, created_at,
    book/chapter titles)."""
    scenes = storyboard.get("scenes", []) or []
    title = storyboard.get("title") or meta.get("chapter_title") or "Chapter"

    return {
        "index.html": _index_html(title, scenes),
        "styles.css": _STYLES,
        "script.js": _SCRIPT,
        "metadata.json": _metadata_json(storyboard, pack, verdict, meta),
    }


def _esc(s) -> str:
    return html.escape(str(s), quote=True)


def _index_html(title: str, scenes: list) -> str:
    # Scene data as a BASE64 island. Why not raw JSON: chapter text legitimately
    # contains 'fetch(' / 'eval(' / '<script>' (CS books!), which would either
    # break out of the <script> block or trip the validator's denylist as a false
    # positive. base64 is [A-Za-z0-9+/=] only — no '<', no forbidden token, no
    # quote to escape. script.js atob+TextDecoder+JSON.parse decodes it (all
    # CSP-safe; no eval). Rendered via textContent, so content is inert (no XSS).
    payload = json.dumps({"title": title, "scenes": scenes}, ensure_ascii=False)
    data = base64.b64encode(payload.encode("utf-8")).decode("ascii")
    total = len(scenes)
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="%s">
<title>%s</title>
<link rel="stylesheet" href="styles.css">
</head>
<body>
<main id="app" aria-live="polite">
  <header>
    <h1>%s</h1>
    <div id="progress" class="progress"><div id="bar" class="bar"></div></div>
    <p id="counter" class="counter"></p>
  </header>
  <section id="scene" class="scene" tabindex="-1"></section>
  <nav class="controls">
    <button id="prev" type="button" aria-label="Previous scene">&larr; Back</button>
    <button id="next" type="button" aria-label="Next scene">Next &rarr;</button>
  </nav>
  <footer><p class="made">Generated by ChapterStage &middot; %d scenes</p></footer>
</main>
<script id="storyboard-data" type="application/json">%s</script>
<script src="script.js"></script>
</body>
</html>
""" % (STRICT_CSP_HEADER, _esc(title), _esc(title), total, data)


_STYLES = """:root{--bg:#0f1226;--panel:#1a1f3d;--ink:#eef0ff;--muted:#9aa3c7;
--accent:#6c8cff;--ok:#39d98a;--bad:#ff6b8b;--ring:#2a3160}
*{box-sizing:border-box}
body{margin:0;font:16px/1.6 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;
background:var(--bg);color:var(--ink)}
#app{max-width:720px;margin:0 auto;padding:24px 18px;min-height:100vh;
display:flex;flex-direction:column}
h1{font-size:1.5rem;margin:.2em 0 .6em}
.progress{height:6px;background:var(--ring);border-radius:6px;overflow:hidden}
.bar{height:100%;width:0;background:var(--accent);transition:width .3s ease}
.counter{color:var(--muted);font-size:.85rem;margin:.4em 0 1em}
.scene{flex:1;background:var(--panel);border:1px solid var(--ring);
border-radius:16px;padding:22px;animation:fade .25s ease}
.scene h2{margin:.1em 0 .5em;font-size:1.25rem}
.scene .body{color:#dfe3ff}
.tag{display:inline-block;font-size:.7rem;letter-spacing:.08em;text-transform:uppercase;
color:var(--accent);border:1px solid var(--ring);border-radius:999px;padding:3px 10px;margin-bottom:10px}
.options{list-style:none;padding:0;margin:14px 0 0;display:grid;gap:10px}
.opt{width:100%;text-align:left;padding:12px 14px;border-radius:12px;
border:1px solid var(--ring);background:#141937;color:var(--ink);cursor:pointer;font:inherit}
.opt:hover{border-color:var(--accent)}
.opt.correct{border-color:var(--ok);background:rgba(57,217,138,.12)}
.opt.wrong{border-color:var(--bad);background:rgba(255,107,139,.12)}
.feedback{margin-top:12px;font-weight:600}
.feedback.ok{color:var(--ok)} .feedback.bad{color:var(--bad)}
.controls{display:flex;gap:12px;margin-top:18px}
.controls button{flex:1;padding:13px;border-radius:12px;border:1px solid var(--ring);
background:var(--accent);color:#0b0e22;font:inherit;font-weight:600;cursor:pointer}
.controls button:disabled{opacity:.4;cursor:not-allowed;background:#3a4160}
#prev{background:#222a52;color:var(--ink)}
.made{color:var(--muted);font-size:.78rem;text-align:center;margin-top:18px}
@keyframes fade{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}
@media(max-width:420px){#app{padding:16px 12px}h1{font-size:1.3rem}}
"""


_SCRIPT = """(function () {
  "use strict";
  var b64 = document.getElementById("storyboard-data").textContent.trim();
  var bin = atob(b64);
  var bytes = new Uint8Array(bin.length);
  for (var j = 0; j < bin.length; j++) { bytes[j] = bin.charCodeAt(j); }
  var data = JSON.parse(new TextDecoder("utf-8").decode(bytes));
  var scenes = (data && data.scenes) || [];
  var i = 0;

  var sceneEl = document.getElementById("scene");
  var prev = document.getElementById("prev");
  var next = document.getElementById("next");
  var bar = document.getElementById("bar");
  var counter = document.getElementById("counter");

  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }

  function renderQuiz(s) {
    var q = el("p", "body", s.question || s.title || "Check your understanding:");
    sceneEl.appendChild(q);
    var ul = el("ul", "options");
    var answered = false;
    (s.options || []).forEach(function (opt, idx) {
      var li = document.createElement("li");
      var b = el("button", "opt", opt);
      b.type = "button";
      b.addEventListener("click", function () {
        if (answered) return;
        answered = true;
        var correct = idx === s.answer_index;
        b.classList.add(correct ? "correct" : "wrong");
        if (!correct) {
          var btns = ul.querySelectorAll(".opt");
          if (btns[s.answer_index]) btns[s.answer_index].classList.add("correct");
        }
        var fb = el("p", "feedback " + (correct ? "ok" : "bad"),
          correct ? "Correct." : "Not quite \\u2014 the highlighted answer is right.");
        sceneEl.appendChild(fb);
      });
      li.appendChild(b);
      ul.appendChild(li);
    });
    sceneEl.appendChild(ul);
  }

  function render() {
    var s = scenes[i] || {};
    sceneEl.innerHTML = "";
    sceneEl.appendChild(el("span", "tag", s.type || "scene"));
    sceneEl.appendChild(el("h2", null, s.title || ("Scene " + (i + 1))));
    if (s.type === "quiz" && s.options) {
      renderQuiz(s);
    } else if (s.body) {
      sceneEl.appendChild(el("p", "body", s.body));
    }
    var pct = scenes.length ? Math.round(((i + 1) / scenes.length) * 100) : 0;
    bar.style.width = pct + "%";
    counter.textContent = "Scene " + (i + 1) + " of " + scenes.length;
    prev.disabled = i === 0;
    next.disabled = i >= scenes.length - 1;
    sceneEl.focus();
  }

  prev.addEventListener("click", function () { if (i > 0) { i--; render(); } });
  next.addEventListener("click", function () {
    if (i < scenes.length - 1) { i++; render(); }
  });
  document.addEventListener("keydown", function (e) {
    if (e.key === "ArrowRight") next.click();
    if (e.key === "ArrowLeft") prev.click();
  });

  render();
})();
"""


def _metadata_json(storyboard, pack, verdict, meta) -> str:
    """Every METADATA_KEYS field the validator requires, populated from the run."""
    payload = {
        "experience_id": meta.get("experience_id", ""),
        "job_id": meta.get("job_id", ""),
        "book_title": meta.get("book_title", ""),
        "chapter_title": meta.get("chapter_title", storyboard.get("title", "")),
        "audience_level": storyboard.get("audience_level", "beginner"),
        "experience_style": storyboard.get("experience_style", "visual_story"),
        "screen_count": storyboard.get("screen_count", len(storyboard.get("scenes", []))),
        "band_room_id": meta.get("band_room_id", ""),
        "selected_brainstorm_variant": meta.get("selected_brainstorm_variant", ""),
        "faithfulness_score": verdict.get("faithfulness_score", 0.0),
        "engagement_score": verdict.get("engagement_score", 0.0),
        "created_at": meta.get("created_at", ""),
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)
